# Use lightweight Python image
FROM python:3.11-alpine

# Copy all app files source to destination
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run Flask app
# CMD ["python", "app.py"]

# Set working directory
# WORKDIR /app

# Expose Flask port
# EXPOSE 5000

